# Generated by Django 4.2.7 on 2023-12-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='translator',
            field=models.ManyToManyField(to='Api.translator'),
        ),
    ]
