# Generated by Django 4.2.7 on 2023-12-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_user_address_user_is_manager_user_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
